export default {
  SEARCH_BAR_TEXT: 'Search your notes',
  PINNED_TEXT: 'Pinned:',
  OTHER_TEXT: 'Others:',
  NOTES_TEXT: 'Notes',
  REMINDER_TEXT: 'Reminders',
  CREATE_NEW_LABEL_TEXT: 'Create new Label',
  ARCHIVE_TEXT: 'Archive',
  DELETE_TEXT: 'Delete',
  LOGOUT_TEXT: 'Logout',
  ENTER_LABEL_NAME_TEXT: 'Enter lable name',
  CREATE_TEXT: 'Create',
  EDITED_TEXT: 'Edited',
  LABELS_TEXT: 'Labels',
  TOMORROW_MORNING_TEXT: 'Tomorrow Morning',
  TOMORROW_EVENING_TEXT: 'Tomorrow Evening',
  TOMORROW_AFTERNOON_TEXT: 'Tomorrow Afternoon',
  PICK_A_DATE_AND_TIME_TEXT: 'Pick a date & time',
  ADD_REMINDER_TEXT: 'Add Reminder',
  CANCEL_TEXT: 'Cancel',
  SIGN_IN_TEXT: 'SignIn',
  SIGN_OUT_TEXT: 'SignOut',
  SIGN_UP_TEXT: 'SignUp',
  REGISTER: 'Register',
  ENTER_USERNAME_TEXT: 'Enter Username ',
  ENTER_PASSWORD_TEXT: 'Enter Password',
  ENTER_EMAIL_TEXT: 'Enter Email ID',
  ENTER_DOB_TEXT: 'Enter Date-of-Birth(DD/MM/YYYY)',
  ENTER_PHONE_NUMBER_TEXT: 'Enter Phone number',
  ENTER_CONFIRM_PASSWORD_TEXT: 'Enter Confirm Password',
  TRASH_TEXT: 'Trash',
  DASHBOARD_TEXT: 'Dashboard',
  SETTING_TEXT: 'Settings',
  APP_DRAWER_TEXT: 'AppDrawer',
  ADD_LABEL_TEXT: 'AddLabel',
  ARCHIVE_EMPTY_TEXT: ' Your achived notes appear here',
  TRASH_EMPTY_TEXT: 'No notes in Trash',
  DASHBOARD_EMPTY_TEXT: 'Notes you added appear here',
  GET_PASSWORD_TEXT: 'Get Password',
  GOOGLE_SIGN_TEXT: 'Sign in with Google',
  FACEBOOK_SIGN_TEXT: 'Sign in with Facebook',
  ADD_ITEM_TEXT: 'Add item',
  CHECKED_ITEM__TEXT: 'Checked item',
  FORGOT_PASSWORD: 'Forgot password',
  EDIT_LABELS_TEXT: 'Edit Labels',
  VALID_EMAIL_ERROR_TEXT: 'Enter Valid Email Id',
  USER_NOT_FOUND: 'User not found',
  INVALID_PASSWORD: 'Invalid Password',
  INVALID_USER: 'Invalid Email',
  VALID_PASSWORD_ERROR_TEXT: 'Enter Valid Password',
  REMINDER_EMPTY_TEXT: 'Notes with upcoming remainders appear here',
};
