export default {
  SEARCH_BAR_TEXT: 'Cerca le tue note',
  PINNED_TEXT: 'Appuntato',
  OTHER_TEXT: 'Altra',
  NOTES_TEXT: 'Nota',
  REMINDER_TEXT: 'Promemoria',
  CREATE_NEW_LABEL_TEXT: 'Crea nuova etichetta',
  ARCHIVE_TEXT: 'Archivio',
  DELETE_TEXT: 'Eliminato',
  LOGOUT_TEXT: 'Disconnettersi',
  ENTER_LABEL_NAME_TEXT: 'Inserisci il nome lable',
  CREATE_TEXT: 'Crea',
  EDITED_TEXT: 'Modificato',
  LABELS_TEXT: 'Etichette',
  EDIT_LABELS_TEXT: 'Modifica etichette',
  TOMORROW_MORNING_TEXT: 'Domani mattina',
  TOMORROW_EVENING_TEXT: 'Domani sera',
  TOMORROW_AFTERNOON_TEXT: 'Domani pomeriggio',
  PICK_A_DATE_AND_TIME_TEXT: "Scegli una data e un'ora",
  ADD_REMINDER_TEXT: 'Aggiungi promemoria',
  CANCEL_TEXT: 'Annulla',
  SIGN_IN_TEXT: 'Accedi',
  SIGN_OUT_TEXT: 'Esci',
  SIGN_UP_TEXT: 'Registrati',
  REGISTER: 'Registrati',
  ENTER_USERNAME_TEXT: 'Inserisci nome utente',
  ENTER_PASSWORD_TEXT: 'Inserisci password',
  ENTER_ENTER_TEXT: 'Inserisci ID e-mail',
  ENTER_DOB_TEXT: 'Immettere la data di nascita (GG/MM/AAAA)',
  ENTER_PHONE_NUMBER_TEXT: 'Inserisci il numero di telefono',
  ENTER_CONFIRM_PASSWORD_TEXT: 'Inserisci conferma password',
  TRASH_TEXT: 'Cestino',
  DASHBOARD_TEXT: 'Dashboard',
  SETTING_TEXT: 'Impostazioni',
  APP_DRAWER_TEXT: 'AppDrawer',
  ADD_LABEL_TEXT: 'AddLabel',
  ARCIVE_EMPTY_TEXT: 'Le tue note acquisite appaiono qui',
  TRASH_EMPTY_TEXT: 'Nessuna nota nel Cestino',
  DASHBOARD_EMPTY_TEXT: 'Le note che hai aggiunto vengono visualizzate qui',
  GET_PASSWORD_TEXT: 'Ottieni password',
  GOOGLE_SIGN_TEXT: 'Accedi con Google',
  FACEBOOK_SIGN_TEXT: 'Accedi con Facebook',
  ADD_ITEM_TEXT: 'Aggiungi elemento',
  CHECKED_ITEM__TEXT: 'Elemento selezionato',
  FORGOT_PASSWORD: 'Forgot password',
  VALID_EMAIL_ERROR_TEXT: 'Inserisci un ID e-mail valido',
  USER_NOT_FOUND: 'Utente non trovato',
  INVALID_PASSWORD: 'Password non valida',
  INVALID_USER: 'Email non valida',
  VALID_PASSWORD_ERROR_TEXT: 'Inserisci password valida',
  REMINDER_EMPTY_TEXT: 'Le note con i resti imminenti appaiono qui',
};
