import {StyleSheet} from 'react-native';
import {
  COLOR,
  PADDING,
  SIZES,
  WIDTH,
  DIRECTION,
  FONT,
  MARGIN,
  BORDER,
  HEIGHT,
  POSITION,
} from './Theme';

export const styles = StyleSheet.create({
  labelView: {
    paddingTop: PADDING.PRIMARY_PADDING,
    borderTopWidth: BORDER.MEDIUM_BORDER,
    borderTopColor: COLOR.SECONDARY,
  },
  space: {flex: SIZES.FLEX + SIZES.FLEX},
  lableInput: {
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
    paddingTop: PADDING.NEGATIVE_PADDING,
    paddingBottom: PADDING.NEGATIVE_PADDING,
    width: WIDTH.FULL_WIDTH,
  },
  labelBox: {
    paddingpaddingLeft: PADDING.paddingLeft_PADDING,
    fontSize: SIZES.MEDIUM_TEXT,
    paddingBottom: PADDING.BOTTOM_PADDING,
    fontWeight: FONT.FONT_WEIGHT,
    color: COLOR.TEXT_COLOR,
  },
  labelList: {
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_ALIGN,
    flexDirection: DIRECTION.FLEX_ROW,
    paddingTop: PADDING.PRIMARY_PADDING,
  },
  editLabel: {
    width: WIDTH.FULL_WIDTH,
    flexDirection: DIRECTION.FLEX_ROW,
    justifyContent: DIRECTION.SPACE_BETWEEN,
    alignContent: DIRECTION.FLEX_ALIGN,
  },
  loader: {
    flex: 1,
    width: WIDTH.FULL_WIDTH,
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
  },
  trashText: {
    color: COLOR.TEXT_COLOR.TEXT_COLOR,
    fontSize: SIZES.LARGE_TEXT,
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
    fontWeight: FONT.FONT_WEIGHT,
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_ALIGN,
  },
  list: {
    width: WIDTH.FULL_WIDTH,
    padding: PADDING.SECONADARY_PADDING,
  },
  grid: {
    alignContent: DIRECTION.FLEX_ALIGN,
    width: WIDTH.HALF_WIDTH,
    paddingBottom: PADDING.SECONADARY_PADDING,
    justifyContent: DIRECTION.FLEX_ALIGN,
  },
  labelText: {
    color: COLOR.TEXT_COLOR,
    fontSize: SIZES.MEDIUM_TEXT,
    fontWeight: FONT.FONT_WEIGHT,
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
  },
  window: {
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignContent: DIRECTION.FLEX_ALIGN,
    width: WIDTH.FULL_WIDTH,
    paddingTop: PADDING.PRIMARY_PADDING,
    paddingBottom: PADDING.SECONADARY_PADDING,
  },
  labelBar: {
    flexDirection: DIRECTION.FLEX_ROW,
    borderBottomWidth: BORDER.MEDIUM_BORDER,
    borderBottomColor: COLOR.TEXT_COLOR,
    width: WIDTH.FULL_WIDTH,
    paddingBottom: PADDING.SECONADARY_PADDING,
    justifyContent: DIRECTION.FLEX_START,
    alignContent: DIRECTION.FLEX_ALIGN,
    height: HEIGHT.BAR_HEIGHT,
    paddingTop: PADDING.SECONADARY_PADDING,
  },
  label: {
    flexDirection: DIRECTION.FLEX_ROW,
    justifyContent: DIRECTION.FLEX_START,
    alignContent: DIRECTION.SPACE_BETWEEN,
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
    paddingTop: PADDING.SECONADARY_PADDING,
  },
  noteBar: {
    justifyContent: DIRECTION.FLEX_START,
    height: HEIGHT.BAR_HEIGHT,
    width: WIDTH.FULL_WIDTH,
    flexDirection: DIRECTION.FLEX_ROW,
    alignContent: DIRECTION.SPACE_BETWEEN,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
  },
  trashBar: {
    backgroundColor: COLOR.SECONDARY,
    height: HEIGHT.BAR_HEIGHT,
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_START,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
    flexDirection: DIRECTION.FLEX_ROW,
  },
  subtitles: {
    color: COLOR.TEXT_COLOR,
    paddingLeft: PADDING.PRIMARY_PADDING,
    paddingTop: PADDING.SECONADARY_PADDING,
    fontSize: SIZES.SMALL_TEXT,
    fontWeight: FONT.FONT_WEIGHT,
  },
  plus: {
    backgroundColor: COLOR.SECONDARY,
    borderRadius: BORDER.BORDER_RADIUS,
    height: HEIGHT.SECTION_HEIGHT,
    width: WIDTH.BUTTON_WIDTH,
    borderWidth: BORDER.THICK_BORDER,
    borderColor: COLOR.PRIMARY,
    borderBottomColor: COLOR.PRIMARY,
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingBottom: PADDING.BUTTON_PADDING,
  },
  icon: {
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
  },
  bottomIcon: {
    paddingpaddingLeft: PADDING.PRIMARY_PADDING,
    flexDirection: DIRECTION.FLEX_ROW,
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
  },
  bottomBar: {
    position: POSITION.ABSOLUTE_POSITION,
    bottom: PADDING.BOTTOM_PADDING,
    width: WIDTH.FULL_WIDTH,
    backgroundColor: COLOR.SECONDARY,
    height: HEIGHT.BAR_HEIGHT,
    flexDirection: DIRECTION.FLEX_ROW,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingLeft: PADDING.SECONADARY_PADDING,
    paddingRight: PADDING.SECONADARY_PADDING,
    justifyContent: DIRECTION.FLEXT_END,
  },
  topBar: {
    justifyContent: DIRECTION.SPACE_AROUND,
    backgroundColor: COLOR.SECONDARY,
    height: HEIGHT.BAR_HEIGHT,
    width: WIDTH.FULL_WIDTH,
    borderRadius: BORDER.ROUND_CORNER,
    flexDirection: DIRECTION.FLEX_ROW,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
  },

  background: {
    flex: SIZES.FLEX,
    backgroundColor: COLOR.PRIMARY,
    alignContent: DIRECTION.FLEX_ALIGN,
    justifyContent: DIRECTION.FLEX_START,
  },
  container: {
    flex: SIZES.FLEX,
    justifyContent: DIRECTION.FLEX_START,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
  },
  logo: {
    paddingTop: PADDING.BUTTON_PADDING,
    alignSelf: DIRECTION.FLEX_ALIGN,
    height: HEIGHT.LOGO_HEIGHT,
    width: WIDTH.LOGO_WIDTH,
    resizeMode: SIZES.IMAGE_RESIZE,
    opacity: SIZES.FLEX,
  },
  output: {
    backgroundColor: COLOR.PRIMARY,
    width: WIDTH.FULL_WIDTH,
    height: HEIGHT.SECTION_HEIGHT,
    borderBottomColor: COLOR.TEXT_COLOR,
    borderBottomWidth: BORDER.THICK_BORDER,
    borderStyle: BORDER.BORDER_STYLE,
    alignItems: DIRECTION.FLEX_ALIGN,
    borderRadius: BORDER.ROUND_CORNER,
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignContent: DIRECTION.FLEX_ALIGN,
    paddingLeft: PADDING.PRIMARY_PADDING,
    textAlign: DIRECTION.FLEX_ALIGN,
    fontWeight: FONT.FONT_WEIGHT,
    color: COLOR.TEXT_COLOR,
    marginBottom: MARGIN.SECONDARY_MARGIN,
    paddingRight: PADDING.PRIMARY_PADDING,
    paddingTop: PADDING.PRIMARY_PADDING,
  },
  title: {
    color: COLOR.TEXT_COLOR,
    fontSize: SIZES.LARGE_TEXT,
    fontWeight: FONT.FONT_WEIGHT,
    paddingLeft: PADDING.PRIMARY_PADDING,
  },
  blank: {
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingLeft: PADDING.PRIMARY_PADDING,
    paddingTop: PADDING.PRIMARY_PADDING,
  },
  blankText: {
    color: COLOR.TEXT_COLOR,
    fontSize: 18,
    alignItems: DIRECTION.FLEX_ALIGN,
    top: 15,
    right: 10,
  },
  flatList: {
    flexWrap: 'wrap',
  },
  middle: {
    flex: 1,
    justifyContent: DIRECTION.FLEX_ALIGN,
    alignContent: DIRECTION.FLEX_ALIGN,
    alignItems: DIRECTION.FLEX_ALIGN,
    paddingLeft: '3%',
  },
  middleText: {
    color: COLOR.TEXT_COLOR,
    fontSize: 20,
    alignItems: DIRECTION.FLEX_ALIGN,
    top: 10,
  },
});
